admins:
  - its core infrastructure
organizations:
  flowerysong:
  its core infrastructure:
  its system support unix:
  its systems support windows:
  virtualization and cloud infrastructure team:
  its infrastructure network software:
