admins:
  - its core infrastructure
organizations:
  ia ansible tower:
  its core infrastructure:
  its is csi smdt:
    teams:
      IAM Core Team:
      IAM Ansible Access:
  its system support unix:
  its systems support windows:
  virtualization and cloud infrastructure team:
  MOS Windows Development:
  its infrastructure network software:
    teams:
      NBIS Admins:
